version: 2.1
jobs:
    build:
        docker:
            - image: python:3.7.3-stretch
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "requirements.txt" }}
                      - v1-dependencies-

            - run:
                  name: Install python dependencies
                  command: |
                      make setup
                      source ~/.devops/bin/activate
                      make install
            - save_cache:
                  key: v1-dependencies-{{ checksum "requirements.txt" }}
                  paths:
                      - ~/.devops

            - run:
                  name: Install hadolint
                  command: |
                      make install-hadolint
            - run:
                  name: Run Lint
                  command: |
                      source ~/.devops/bin/activate
                      make lint
            
workflows:
    main:
        jobs:
            - build
